name: Windows

on:
  workflow_call:

jobs:
  build:
    env:
      MILODY_TARGET_OS: "windows"
      MILODY_TARGET_ARCH: "amd64"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      # - name: Add MSBuild to PATH
      #   uses: microsoft/setup-msbuild@v1.1

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.11.1
          
      - uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: Run CMake configuration for Game
        shell: cmd
        run: |
          cmake -S . -B build_game ^
          -GNinja ^
          -DCMAKE_C_COMPILER=cl.exe ^
          -DCMAKE_CXX_COMPILER=cl.exe ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DMILODY_ENABLE_CLI=OFF ^
          -DMILODY_ENABLE_TESTS=OFF ^
          -DMILODY_BUILD_SHARED_LIBS=ON ^
          -DCMAKE_INSTALL_PREFIX=./milody-game

      - name: Build Game Library
        run: cmake --build build_game --target install

      - name: Package Game Library
        shell: pwsh
        run: Compress-Archive -Path milody-game -DestinationPath "milody-game-${{ env.MILODY_TARGET_OS }}-${{ env.MILODY_TARGET_ARCH }}.zip"

      - name: Upload Game Artifact
        uses: actions/upload-artifact@v4
        with:
          name: milody-game-${{ env.MILODY_TARGET_OS }}-${{ env.MILODY_TARGET_ARCH }}
          path: milody-game-${{ env.MILODY_TARGET_OS }}-${{ env.MILODY_TARGET_ARCH }}.zip
          retention-days: 30
